openapi: 3.0.0
info:
  contact:
    email: support@icdc.io
  description: Oopen API for S3 storage server
  title: S3 Storage service
  version: 0.0.1
servers:
- url: http://localhost:8080/storage/s3
security:
- bearerAuth: []
paths:
  /accounts/{account}:
    get:
      description: 'Returns account quota, information about allocated resources and
        if include_usage parameter is true then also actual resource usage. Only account
        admins are authorized to get this information '
      operationId: accounts_account_get
      parameters:
      - description: account name for which information should be returned, e.g. dep2
        explode: false
        in: path
        name: account
        required: true
        schema:
          type: string
        style: simple
      - description: Whether or not include actual storage  usage for the account.
          Default is false, because this is a long operation and we do not always
          need it
        explode: true
        in: query
        name: include_usage
        required: false
        schema:
          type: boolean
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/s3_account_info'
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Account not found
      summary: Get account information
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
  /accounts/{account}/s3users:
    get:
      description: List of s3 users with the details The calls can be issued either
        by account admins or by account members. Account admins will see all s3users
        for the account. Account members will only see s3users, which they own
      operationId: accounts_account_s3users_get
      parameters:
      - explode: false
        in: path
        name: account
        required: true
        schema:
          type: string
        style: simple
      - description: Indicates that we only need to return s3 users owned by specified
          account member. Not sure where we need it at the moment, just in case...
        explode: true
        in: query
        name: account_user
        required: false
        schema:
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/s3users_list'
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: No users found for this account
      summary: Get s3 users list for the account
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
    put:
      description: Create s3 user in specified account. Only account admins are allowed
        to do this, unless number of s3users in member quota of the account is not
        zero
      operationId: accounts_account_s3users_put
      parameters:
      - explode: false
        in: path
        name: account
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/s3user_create_or_update_request'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/s3user'
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Bad request, e.g user exists or quota exceeded
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
      summary: Create s3 user in specified account
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
  /accounts/{account}/{account_member}:
    get:
      description: Returns information how many and with which quota account member
        (not admins) can create s3 users and how many s3users has been created already
        by the specified member
      operationId: accounts_account_account_member_get
      parameters:
      - explode: false
        in: path
        name: account
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: account_member
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account_member_quota_info'
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Account not found
      summary: Returns information how many and with which quota account member can
        create s3 users
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
  /s3users/{s3_user}:
    delete:
      description: Delete s3 user and all the data.  Account admins can delete any
        s3 user in the account. Account members can only delete s3user, which they
        own
      operationId: s3users_s3_user_delete
      parameters:
      - description: Registered s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User does not exist
      summary: Delete s3 user
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
    get:
      description: Get s3 user information.  Account admins can get information for
        any s3 user in the account. Account members can only get information for the
        s3 users which they own
      operationId: s3users_s3_user_get
      parameters:
      - description: s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/s3user'
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User not found in this account
      summary: Get s3 user information
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
    put:
      description: Modify s3 user.  Account admins can modify any s3 user in the account.
        Account members can only modify s3user_description, max_buckets and default_quota_per_bucket
        properties for s3users which they own
      operationId: s3users_s3_user_put
      parameters:
      - description: s3user name, which sould be updated
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/s3user_create_or_update_request'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/s3user'
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Bad request, e.g. quota exceeded
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User not found for this account
      summary: Modify s3 user
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
  /s3users/{s3_user}/buckets:
    get:
      description: Get list of buckets for s3 user. Can be done either by account
        admin or account member who own s3user. This operation can also be done via
        S3 REST api by anyone who knows access and secret keys or swift user id and
        swift secret key.
      operationId: s3users_s3_user_buckets_get
      parameters:
      - description: Registered s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/bucket_info'
                type: array
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User does not exist or no buckets for the user
      summary: Get list of buckets for s3 user
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
    put:
      description: Create bucket for s3 user. Can be done either by account admin
        or account member who owns s3user.  Buckets can also be created by S3 api,
        but in order to control quota such buckets will be created with almost zero
        quota. So, to use such buckets user at first will have to increase the bucket
        quota via our UI.
      operationId: s3users_s3_user_buckets_put
      parameters:
      - description: Registered s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bucket_create_or_update_request'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bucket_info'
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Bad request, e.g user exists or quota exceeded
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User does not exist
      summary: Create a new bucket
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
  /s3users/{s3_user}/buckets/{bucket_name}:
    delete:
      description: Delete a bucket with all the data. Can be done either by account
        admin or account member who owns s3user.
      operationId: s3users_s3_user_buckets_bucket_name_delete
      parameters:
      - description: Registered s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: bucket_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            text/plain:
              schema:
                type: string
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User does not exist
      summary: Delete a bucket with all the data
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
    get:
      description: Get buckets details for s3 user. Can be done either by account
        admin or account member who own s3user. This operation can also be done via
        S3 REST api by anyone who knows access and secret keys or swift user id and
        swift secret key.
      operationId: s3users_s3_user_buckets_bucket_name_get
      parameters:
      - description: Registered s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: bucket_name
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/bucket_info'
                type: array
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User does not exist or no buckets for the user
      summary: Get buckets details for s3 user
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
    put:
      description: Change an existing bucket. Can be done either by account admin
        or account member who owns s3user. With this call we can change only bucket
        quota
      operationId: s3users_s3_user_buckets_bucket_name_put
      parameters:
      - description: Registered s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: bucket_name
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bucket_create_or_update_request'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bucket_info'
          description: OK
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Bad request, e.g user exists or quota exceeded
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User does not exist
      summary: Change an existing bucket
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
  /s3users/{s3_user}/keys:
    put:
      description: Re-generate s3 user access and secret keys as well as swift key.
        Account admins can do this for any s3 user in the account. Account members
        can only re-generate keys for s3user which they own
      operationId: s3users_s3_user_keys_put
      parameters:
      - description: Registered s3 user name
        explode: false
        in: path
        name: s3_user
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/s3user'
          description: OK
        401:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: Unauthorized
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error4xx'
          description: User does not exist
      summary: Re-generate s3 user access and secret keys as well as swift key
      x-openapi-router-controller: storage.openapi_app.controllers.s3_controller
components:
  schemas:
    error4xx:
      properties:
        bad_item:
          type: string
        explanation:
          type: string
      required:
      - bad_item
      - explanation
      type: object
    storage_quota_or_usage:
      description: Depending on usecase either quota or actual usage
      example:
        data_size: 7
        number_of_objects: 2
      properties:
        number_of_objects:
          description: Number of objects
          format: int64
          type: integer
        data_size:
          description: data size
          format: int64
          type: integer
      required:
      - data_size
      - number_of_objects
      type: object
    bucket_create_or_update_request:
      properties:
        s3user_name:
          type: string
        bucket_name:
          type: string
        quota:
          $ref: '#/components/schemas/storage_quota_or_usage'
        bucket_properties:
          type: object
      required:
      - bucket_name
      - s3user_name
      type: object
    bucket_info:
      example:
        bucket_properties: '{}'
        actual_usage:
          data_size: 7
          number_of_objects: 2
        bucket_name: bucket_name
        quota:
          data_size: 7
          number_of_objects: 2
        s3user_name: s3user_name
      properties:
        s3user_name:
          type: string
        bucket_name:
          type: string
        quota:
          $ref: '#/components/schemas/storage_quota_or_usage'
        actual_usage:
          $ref: '#/components/schemas/storage_quota_or_usage'
        bucket_properties:
          description: For future use. To keep ACLs, bucket policy and all other things
          type: object
      required:
      - actual_usage
      - bucket_name
      - quota
      - s3user_name
      type: object
    s3user_quota_or_usage:
      description: Depending on situtation either a quota or current usage
      example:
        data_size: 6
        number_of_objects: 0
        number_of_buckets: 1
      properties:
        number_of_objects:
          description: Number of objects
          format: int64
          type: integer
        data_size:
          description: data size in bytes
          format: int64
          type: integer
        number_of_buckets:
          format: int32
          type: integer
      required:
      - data_size
      - number_of_buckets
      - number_of_objects
      type: object
    s3user_create_or_update_request:
      properties:
        account:
          description: Account in which user is created. The field is immutable after
            creation
          type: string
        owner:
          description: Name of the account member, who will own the s3user. If emty
            then s3user will be visible only for  account admins
          type: string
        s3user_name:
          description: The field is Immutable after creation
          type: string
        s3user_description:
          type: string
        quota_per_s3user:
          $ref: '#/components/schemas/s3user_quota_or_usage'
        default_quota_per_bucket:
          $ref: '#/components/schemas/storage_quota_or_usage'
      required:
      - account
      - quota_per_s3user
      - s3user_description
      - s3user_name
      type: object
    s3user:
      example:
        owner: owner
        secret_key: secret_key
        current_actual_usage:
          data_size: 6
          number_of_objects: 0
          number_of_buckets: 1
        swift_key: swift_key
        access_key: access_key
        s3user_name: s3user_name
        quota_per_s3user:
          data_size: 6
          number_of_objects: 0
          number_of_buckets: 1
        swift_id: swift_id
        default_quota_per_bucket:
          data_size: 7
          number_of_objects: 2
        account: account
        s3user_description: s3user_description
      properties:
        account:
          type: string
        owner:
          description: Name of the account member, who owns the s3user. If emty then
            s3user will be visible only for  account admins
          type: string
        s3user_name:
          type: string
        s3user_description:
          type: string
        secret_key:
          type: string
        access_key:
          type: string
        swift_id:
          type: string
        swift_key:
          type: string
        default_quota_per_bucket:
          $ref: '#/components/schemas/storage_quota_or_usage'
        quota_per_s3user:
          $ref: '#/components/schemas/s3user_quota_or_usage'
        current_actual_usage:
          $ref: '#/components/schemas/s3user_quota_or_usage'
      required:
      - access_key
      - account
      - current_actual_usage
      - default_quota_per_bucket
      - quota_per_s3user
      - s3user_description
      - s3user_name
      - secret_key
      - swift_id
      - swift_key
      type: object
    s3users_list:
      items:
        $ref: '#/components/schemas/s3user'
      type: array
    account_quota:
      example:
        data_size: 6
        number_of_objects: 0
        number_of_buckets_per_s3user: 1
        number_of_s3users: 5
      properties:
        number_of_objects:
          description: Number of objects
          format: int64
          type: integer
        data_size:
          description: data size in bytes
          format: int64
          type: integer
        number_of_buckets_per_s3user:
          format: int32
          type: integer
        number_of_s3users:
          format: int64
          type: integer
      required:
      - data_size
      - number_of_buckets_per_s3user
      - number_of_objects
      - number_of_s3users
    s3_account_info:
      example:
        actual_storage_usage:
          data_size: 7
          number_of_objects: 2
        account_total_quota:
          data_size: 6
          number_of_objects: 0
          number_of_buckets_per_s3user: 1
          number_of_s3users: 5
        member_quota:
          data_size: 6
          number_of_objects: 0
          number_of_buckets_per_s3user: 1
          number_of_s3users: 5
        account: account
        current_number_of_s3users: 5
      properties:
        account:
          type: string
        account_total_quota:
          $ref: '#/components/schemas/account_quota'
        member_quota:
          $ref: '#/components/schemas/account_quota'
        current_number_of_s3users:
          format: int64
          type: integer
        actual_storage_usage:
          $ref: '#/components/schemas/storage_quota_or_usage'
      required:
      - account
      - account_total_quota
      - current_number_of_s3users
      - member_quota
      type: object
    account_member_quota_info:
      description: Information, which identifies whether account member is allowed
        to create more s3 usersand with which quota
      example:
        account_member_quota:
          data_size: 6
          number_of_objects: 0
          number_of_buckets_per_s3user: 1
          number_of_s3users: 5
        number_of_created_s3users: 0
        account_member: account_member
        account: account
      properties:
        account:
          type: string
        account_member:
          type: string
        account_member_quota:
          $ref: '#/components/schemas/account_quota'
        number_of_created_s3users:
          format: int32
          type: integer
      required:
      - account
      - account_member
      - account_member_quota
      - number_of_created_s3users
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: storage.openapi_app.controllers.security_controller_.info_from_bearerAuth
